### ISSUE TITLE
Tornado gives WebSocketClosedError

### ISSUE THREAD

**Issue by tlkh** [NVAITC/ai-lab#8]
**Describe the bug**

Tornado gives `WebSocketClosedError` constantly but the notebook environment seems to be fine. Strange behaviour.

```
[E 06:36:44.455 NotebookApp] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(58c3a0b8-fed0-4680-897a-833a1b543566)>
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 189, in send_ping
        self.ping(b'')
      File "/opt/conda/lib/python3.6/site-packages/tornado/websocket.py", line 447, in ping
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
```

**To Reproduce**

Use container `0.7-test`

**Expected behavior**

Not give the error message

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows/macOS] Ubuntu 18.04
 - Browser [e.g. Chrome, Safari] Chrome

**Container Version**

`nvaitc/ai-lab:0.7-test`

**Additional context**

**Comment by tlkh** [comment]
Seems to be an isolated incident that never appears again after container is restarted.
